#!/usr/bin/perl -w

use strict;
use warnings;
use feature 'switch';

use Carp qw(croak);

use lib "$ENV{HOME}/mb/bot/lib";
use lib "$ENV{HOME}/mb/server/cgi-bin";

use MusicBrainz;
use Sql;
use Log::Dispatch;
use Log::Dispatch::Screen;

my $log = Log::Dispatch->new;
$log->add ( Log::Dispatch::Screen->new ( name => 'debugscreen', min_level => 'debug' ) );

my $mb = MusicBrainz->new;
$mb->Login();
my $sql = Sql->new($mb->{DBH});

my $tasks = $sql->SelectListOfHashes('SELECT schema, task FROM mbot.tasks WHERE last_replication + frequency <= mbot.replseq() ORDER BY priority, task');

foreach my $taskrow (@{$tasks}) {
	my $task = $taskrow->{'task'};
	my $schema = $taskrow->{'schema'};
	
	$log->info(localtime() . " : Running task '$task'.\n");
	
	my $tasktable;
	my $taskschema = $schema;
	
	my $countdiff = 1;
	
	given ($task) {
		when (/^upd_(.*)/) { $tasktable = $1; }
		when (/^(tmp_.*)/) { $tasktable = $1; $countdiff = 0; }
		when (/^find_edits/) { $tasktable = 'edits'; $taskschema = 'mbot'; }
		when (/^find_spider/) { $tasktable = 'tasks'; $taskschema = 'mspider'; }
		
		default { croak 'Unknown task type'; }
	}
	
	my $beforecount = $sql->SelectSingleValue("SELECT COUNT(*) FROM $taskschema.$tasktable") if $countdiff;
	
	$sql->SelectSingleValue("SELECT $schema.$task()");
	
	my $aftercount  = $sql->SelectSingleValue("SELECT COUNT(*) FROM $taskschema.$tasktable");
	my $diff;
	
	if ($countdiff) {
		$diff = $aftercount - $beforecount;
		if ($diff >= 0) { $diff = '+' . $diff; }
	} else {
		$diff = $aftercount;
	}
	
	$log->info(localtime() . " : Row count = $diff\n");
}

$log->info(localtime() . " : Done.\n");
