#!/usr/bin/perl -w

use lib "$ENV{HOME}/mb/bot/lib";
use lib "$ENV{HOME}/mb/server/cgi-bin";

use MusicBrainz;
use Sql;
use Log::Dispatch;
use Log::Dispatch::Screen;

my $log = Log::Dispatch->new;
$log->add ( Log::Dispatch::Screen->new ( name => 'debugscreen', min_level => 'debug' ) );

my $mb = new MusicBrainz;
$mb->Login();
my $sql = new Sql($mb->{DBH});

my $editsbefore = $sql->SelectSingleValue('SELECT COUNT(*) FROM mbot.edits');

my $tasks = $sql->SelectSingleColumnArray('SELECT task FROM mbot.tasks WHERE last_replication + frequency <= mbot.replseq() ORDER BY priority, task');

foreach my $task (@{$tasks}) {
	$log->info(localtime() . " : Running task '$task'.\n");
	
	if ($task =~ /^upd_(.*)/) {
		$tasktable = $1;
		my $beforecount = $sql->SelectSingleValue("SELECT COUNT(*) FROM mbot.$tasktable");
		
		$sql->SelectSingleValue("SELECT mbot.$task()");
		
		my $aftercount  = $sql->SelectSingleValue("SELECT COUNT(*) FROM mbot.$tasktable");
		my $diff = $aftercount - $beforecount;
		if ($diff >= 0) { $diff = '+' . $diff; }
		$log->info(localtime() . " : Row count = $diff\n");
	} elsif ($task =~ /^(tmp_.*)/) {
		$tasktable = $1;
		$sql->SelectSingleValue("SELECT mbot.$task()");
		
		my $aftercount  = $sql->SelectSingleValue("SELECT COUNT(*) FROM mbot.$tasktable");
		$log->info(localtime() . " : Row count = $aftercount\n");
	} else {
		$sql->SelectSingleValue("SELECT mbot.$task()");
	}
}

my $editsafter = $sql->SelectSingleValue('SELECT COUNT(*) FROM mbot.edits');
my $editsdiff = $editsafter - $editsbefore;

my $status = 'No new edits.';
if ($editsdiff > 0) { $status = "$editsdiff new edits."; }
elsif ($editsdiff < 0) { $editsdiff = -$editsdiff; $status = "$editsdiff edits removed."; }

$log->info(localtime() . " : Done. $status\n");
